[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "norbok"
version = "0.1.1"
requires-python = ">3.9"
dependencies = [
    "openai",
    "rich",
    "prompt-toolkit",
    "pygments",
]

[project.scripts]
norbok = "norbok.main:run"

[tool.setuptools.packages.find]
include = ["norbok*"]